## 1. Import libraries

In [1]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import plotly.express as px

In [2]:
import pandas as pd
import xlrd
from geopy.geocoders import Nominatim

In [3]:
import pandas as pd
import numpy as np
import sys
sys.path.append("../")

## 2. Import Data

In [4]:
subdata0 = pd.read_csv("../Data/subdata0.csv")

In [5]:
subdata1 = pd.read_csv("../Data/subdata1.csv")

In [6]:
subdata2 = pd.read_csv("../Data/subdata2.csv")

### We will eliminate the columns that we have already used previously in the profile determination.

In [7]:
subdata0.drop(['Unnamed: 0','Gun_related_deaths','VAT_Sales_Tax','GDP_per_capita', 'Growth_percentage','Unemployment_percentage','Housing', 'Culture','Travel_connectivity','Sport_venues'], axis=1, inplace=True)

In [8]:
subdata1.drop(['Unnamed: 0','Gun_related_deaths','VAT_Sales_Tax','GDP_per_capita', 'Growth_percentage','Unemployment_percentage','Housing', 'Culture','Travel_connectivity','Sport_venues'], axis=1, inplace=True)

In [9]:
subdata2.drop(['Unnamed: 0','Gun_related_deaths','VAT_Sales_Tax','GDP_per_capita', 'Growth_percentage','Unemployment_percentage','Housing', 'Culture','Travel_connectivity','Sport_venues'], axis=1, inplace=True)

In [10]:
New_names = {"Pisa_ranking": "Education_Ranking", "Homosexuality_acceptance":"Tolerance","Average_Annual_percent_sunshine": "Average_Annual_sunshine","predict": "Cluster"}

In [11]:
subdata0.rename(columns=New_names, inplace=True)

In [12]:
subdata1.rename(columns=New_names, inplace=True)

In [13]:
subdata2.rename(columns=New_names, inplace=True)

In [14]:
subdata1.head()

Education_Ranking     Cities  Tolerance  Average_Annual_sunshine  Cluster
0                 13     Aarhus      93.03                      0.0        1
1                 16   Adelaide      79.00                     12.6        1
2                 10  Amsterdam      97.37                     12.9        1
3                 12   Auckland      93.65                    182.9        1
4                 22  Barcelona      88.00                     73.0        1

In [34]:
subdata0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Education_Ranking        90 non-null     int64  
 1   Cities                   90 non-null     object 
 2   Tolerance                90 non-null     float64
 3   Average_Annual_sunshine  90 non-null     float64
 4   Cluster                  90 non-null     int64  
 5   Escala_de_Educacion      90 non-null     object 
dtypes: float64(2), int64(2), object(2)
memory usage: 4.3+ KB


In [35]:
subdata0["Tolerance"] = subdata0["Tolerance"].astype(dtype=int)

In [36]:
subdata1["Tolerance"] = subdata1["Tolerance"].astype(dtype=int)

In [37]:
subdata2["Tolerance"] = subdata2["Tolerance"].astype(dtype=int)

In [39]:
subdata0["Average_Annual_sunshine"] = subdata0["Average_Annual_sunshine"].astype(dtype=int)

In [40]:
subdata1["Average_Annual_sunshine"] = subdata1["Average_Annual_sunshine"].astype(dtype=int)

In [41]:
subdata2["Average_Annual_sunshine"] = subdata2["Average_Annual_sunshine"].astype(dtype=int)

## 3. We assign values through intervals to be used as a filter for the user.

### 3.1 Education_Ranking

In [18]:
def intervalos_edu(i):
        if i < 25:
            i = str("Alto")
        elif i > 25 & i > 40:
            i = str("Medio")
        else:
            i = str("Bajo")
        return i

In [15]:
subdata0.Education_Ranking.unique()

array([39,  0, 43, 35, 48, 24, 47,  8, 51, 40, 31, 52, 14, 41, 22, 38, 18,
       46, 34, 21, 25, 37, 36,  4, 49, 30, 10])

In [16]:
subdata0.Education_Ranking.max()

52

*Observamos que el máximo en el ranking a nivel educativo es el puesto 52, que seria el puesto más alto dentro de este cluster.* 

In [19]:
# a 0 le pondria "Nulo" pero no me deja poner otro elif sin que me de error de sintaxis

In [20]:
subdata0["Escala_de_Educacion"] = subdata0.Education_Ranking.apply(intervalos_edu0)

In [21]:
subdata0.head()

Education_Ranking    Cities  Tolerance  Average_Annual_sunshine  Cluster  \
0                 39    Almaty      66.56                     64.0        0   
1                  0   Andorra      73.05                      0.0        0   
2                 43    Ankara       9.00                    243.0        0   
3                  0  Asuncion      49.54                     12.5        0   
4                 35    Athens      53.00                    266.7        0   

  Escala_de_Educacion  
0                Bajo  
1                Alto  
2                Bajo  
3                Alto  
4                Bajo

In [82]:
subdata0.Escala_de_Educacion.value_counts()

Alto    57
Bajo    33
Name: Escala_de_Educacion, dtype: int64

In [22]:
subdata1.Education_Ranking.unique()

array([13, 16, 10, 12, 22, 17, 26, 19, 34, 21, 15,  5,  9,  3,  6, 20, 39,
       28,  7, 32,  0])

In [23]:
subdata1.Education_Ranking.max()

39

In [24]:
subdata1["Escala_de_Educacion"] = subdata1.Education_Ranking.apply(intervalos_edu)

In [25]:
subdata1.head()

Education_Ranking     Cities  Tolerance  Average_Annual_sunshine  Cluster  \
0                 13     Aarhus      93.03                      0.0        1   
1                 16   Adelaide      79.00                     12.6        1   
2                 10  Amsterdam      97.37                     12.9        1   
3                 12   Auckland      93.65                    182.9        1   
4                 22  Barcelona      88.00                     73.0        1   

  Escala_de_Educacion  
0                Alto  
1                Alto  
2                Alto  
3                Alto  
4                Alto

In [81]:
subdata1.Escala_de_Educacion.value_counts()

Alto    87
Bajo    10
Name: Escala_de_Educacion, dtype: int64

In [26]:
subdata2.Education_Ranking.unique()

array([24, 16, 13, 11,  9, 49, 41,  2, 25,  0,  1])

In [27]:
subdata2.Education_Ranking.max()

49

In [28]:
subdata2["Escala_de_Educacion"] = subdata2.Education_Ranking.apply(intervalos_edu)

In [29]:
subdata2.head()

Education_Ranking       Cities  Tolerance  Average_Annual_sunshine  \
0                 24  Albuquerque      93.13                    168.0   
1                 16    Anchorage      76.56                     61.0   
2                 16    Asheville      67.58                    101.0   
3                 24      Atlanta      70.00                    110.0   
4                 24       Austin      64.44                    116.0   

   Cluster Escala_de_Educacion  
0        2                Alto  
1        2                Alto  
2        2                Alto  
3        2                Alto  
4        2                Alto

In [80]:
subdata2.Escala_de_Educacion.value_counts()

Alto    72
Bajo     3
Name: Escala_de_Educacion, dtype: int64

### 3.2 Tolerance

In [42]:
def intervalos_tolerance(i):
        if i < 75:
            i = str("Alto")
        elif i > 75 & i > 40:
            i = str("Medio")
        else:
            i = str("Bajo")
        return i

In [30]:
subdata0.Tolerance.unique()

array([66.56, 73.05,  9.  , 49.54, 53.  , 43.77,  3.  , 96.88, 61.15,
       21.  , 18.  , 75.85, 24.29, 89.16, 77.95, 80.34, 74.  , 32.  ,
       51.  ,  9.29, 71.12, 60.  , 26.32, 42.  , 89.  , 61.  , 80.03,
       78.65, 55.27, 87.91, 71.98, 34.67,  1.  , 43.  , 69.04, 95.36,
       83.04, 73.  , 56.93, 96.4 , 16.  ,  8.  ,  0.  , 60.76, 55.34,
       86.69, 74.15, 77.43, 34.  , 68.  , 41.72, 78.59, 61.3 , 79.88,
       75.08, 47.99, 80.63, 10.42, 23.49, 82.2 , 59.44, 80.17])

In [31]:
subdata0.Tolerance.max()

96.88

In [43]:
subdata0["Escala_de_Tolerancia"] = subdata0.Tolerance.apply(intervalos_tolerance)

In [44]:
subdata0.head()

Education_Ranking    Cities  Tolerance  Average_Annual_sunshine  Cluster  \
0                 39    Almaty         66                       64        0   
1                  0   Andorra         73                        0        0   
2                 43    Ankara          9                      243        0   
3                  0  Asuncion         49                       12        0   
4                 35    Athens         53                      266        0   

  Escala_de_Educacion Escala_de_Tolerancia  
0                Bajo                 Alto  
1                Alto                 Alto  
2                Bajo                 Alto  
3                Alto                 Alto  
4                Bajo                 Alto

In [79]:
subdata0.Escala_de_Tolerancia.value_counts()

Alto     66
Medio    21
Bajo      3
Name: Escala_de_Tolerancia, dtype: int64

In [45]:
subdata1.Tolerance.unique()

array([93, 79, 97, 88, 76, 87, 74, 77, 69, 81, 92, 80, 54, 70, 73, 39, 66,
       40])

In [46]:
subdata1.Tolerance.max()

97

In [47]:
subdata1["Escala_de_Tolerancia"] = subdata1.Tolerance.apply(intervalos_tolerance)

In [78]:
subdata1.Escala_de_Tolerancia.value_counts()

Medio    81
Alto     16
Name: Escala_de_Tolerancia, dtype: int64

In [48]:
subdata2.Tolerance.unique()

array([ 93,  76,  67,  70,  64,  81,  72,  96,  50,  86,  66,  85,  63,
        15,  23,  55,  71,  89,  82,  80,   3,  92,  91,  31, 100])

In [49]:
subdata2.Tolerance.max()

100

In [50]:
subdata2["Escala_de_Tolerancia"] = subdata2.Tolerance.apply(intervalos_tolerance)

In [77]:
subdata2.Escala_de_Tolerancia.value_counts()

Medio    38
Alto     37
Name: Escala_de_Tolerancia, dtype: int64

### 3.3 Average_Annual_sunshine

In [56]:
def intervalos_sun(i):
        if i < 240:
            i = str("Alto")
        elif i > 240 & i > 130:
            i = str("Medio")
        else:
            i = str("Bajo")
        return i

In [57]:
subdata0.Average_Annual_sunshine.unique()

array([ 64,   0, 243,  12, 266, 207,  75, 124, 254, 260, 228, 225, 181,
       277, 222, 265, 246, 217, 312, 218,  31, 252,  13, 302, 102, 282,
       242, 271,  70, 236, 113,  49, 286])

In [58]:
subdata0.Average_Annual_sunshine.max()

312

In [59]:
subdata0["Escala_de_Sunshine"] = subdata0.Average_Annual_sunshine.apply(intervalos_sun)

In [76]:
subdata0.Escala_de_Sunshine.value_counts()

Alto     76
Bajo      9
Medio     5
Name: Escala_de_Sunshine, dtype: int64

In [60]:
subdata1.Average_Annual_sunshine.unique()

array([  0,  12, 182,  73, 209, 160,  35, 288, 116, 297, 238, 138,  13,
       298, 227, 281, 282, 302,  90, 198, 200, 296, 285,  65,  91, 290,
        89, 241,  94, 107, 336, 246, 180, 130, 299, 250, 129, 161, 287,
       291, 199, 213, 172])

In [61]:
subdata1.Average_Annual_sunshine.max()

336

In [62]:
subdata1["Escala_de_Sunshine"] = subdata1.Average_Annual_sunshine.apply(intervalos_sun)

In [72]:
subdata1.Escala_de_Sunshine.value_counts()

Alto     79
Bajo     15
Medio     3
Name: Escala_de_Sunshine, dtype: int64

In [63]:
subdata2.Average_Annual_sunshine.unique()

array([168,  61, 101, 110, 116, 113, 213, 120,  98, 324, 326,  54, 259,
       111, 105,  84,  82,  66, 127,  72, 161, 136, 115,  76,  12, 337,
       174,  75, 330,  44,  90,  91,  88,  95, 121,  97, 211,   0, 147,
        93, 118,  96, 103, 107, 139, 177,  58,  68,  99, 100, 125, 106,
       298,  71, 102,  36])

In [64]:
subdata2.Average_Annual_sunshine.max()

337

In [74]:
subdata2["Escala_de_Sunshine"] = subdata2.Average_Annual_sunshine.apply(intervalos_sun)

In [75]:
subdata2.Escala_de_Sunshine.value_counts()

Alto    68
Bajo     7
Name: Escala_de_Sunshine, dtype: int64

In [83]:
Innovator = subdata0

In [84]:
Traveler = subdata1

In [85]:
Posh = subdata2

In [87]:
Innovator.to_csv("../Data/Innovator.csv")

In [88]:
Traveler.to_csv("../Data/Traveler.csv")

In [89]:
Posh.to_csv("../Data/Posh.csv")